apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: bitnami/nginx:latest
        name: web-server
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          capabilities:
            add:
            - NET_RAW
